import { Routes } from '@angular/router';
import { LoginComponent } from './pages/login/login';
import { DashboardComponent } from './pages/dashboard/dashboard';
import { AppelsOffresComponent } from './pages/appels-offres/appels-offres';
import { Marches } from './pages/marches/marches';
import { Commandes } from './pages/commandes/commandes';
import { Paiements } from './pages/paiements/paiements';
import { Clients } from './pages/clients/clients';
import { Consultations } from './pages/consultations/consultations';
import { Notifications } from './pages/notifications/notifications';
import { Offres } from './pages/offres/offres';
import { OrdresService } from './pages/ordres-service/ordres-service';
import { BonsLivraison } from './pages/bons-livraison/bons-livraison';
import { Factures } from './pages/factures/factures';
import { Statistiques } from './pages/statistiques/statistiques';

export const routes: Routes = [
  { path: '', component: LoginComponent },
  { path: 'login', component: LoginComponent },
  { path: 'dashboard', component: DashboardComponent },
  { path: 'notifications', component: Notifications },
  { path: 'appels-offres', component: AppelsOffresComponent },
  { path: 'marches', component: Marches },
  { path: 'ordres-service', component: OrdresService },
  { path: 'commandes', component: Commandes },
  { path: 'bons-livraison', component: BonsLivraison },
  { path: 'factures', component: Factures },
  { path: 'paiements', component: Paiements },
  { path: 'clients', component: Clients },
  { path: 'consultations', component: Consultations },
  { path: 'offres', component: Offres },
  { path: 'statistiques', component: Statistiques }
];
